---
repos:
  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        minimum_pre_commit_version: 2.4.0
        language: golang
        additional_dependencies: [mvdan.cc/sh/v3/cmd/shfmt@v3.2.2]
        entry: shfmt
        args: [-l, -w, -i=2, -bn, -ci, -sr, -kp]
        types: [shell]
